### ISSUE TITLE
handlebarsjs.com - SSL Broken

### ISSUE THREAD

**Issue by realtruckjoshdeltener** [wycats/handlebars-site#175] opened 2017-03-14 16:22 UTC
Just a heads up, the ssl on handlebarsjs.com is broken.  it's issued to github.com, not your domain, thus giant error pages are shown on any modern browser :(

**Comment by nknapp** [comment] 2017-10-06 20:56
This is a duplicate of #171.

**Closed by nknapp** 2017-10-06 20:56 UTC
