### ISSUE TITLE
Site navigation

### ISSUE THREAD

**Issue by AKarmanov** [wycats/handlebars-site#192] opened 2018-06-29 11:35 UTC
Do you guys realize that your site doesn't have a way to navigate it? There is no menu or anything like that. Searching for docs is incredibly difficult! Add links to different sections like references, helpers etc. at least in the footer.

**Comment by nknapp** [comment] 2018-07-03 21:15
Yes, there should be a new site and we had an attempt to start on. But somebody would have to spend a lot of time for that, and at the moment, that is something I don't have.

Duplicate of #180  #160 

If any progress will be made, it is in https://github.com/handlebars-lang, but at the moment, it's rather stalling.

**Comment by milenvoutchev** [comment] 2019-04-11 10:31
Documentation, could be said, is sub-par. However, with better tools it can be navigated and searched easily. I've found https://devdocs.io/handlebars to be of great help. Hope this helps!

**Comment by nknapp** [comment] 2019-04-29 22:09
I have created a new draft site at https://handlebars-lang.github.io/docs/. You can help by making pull requests copying content from the old site.

**Comment by nknapp** [comment] 2019-11-23 16:25
new site is up, https still needs some time.

**Closed by nknapp** 2019-11-23 16:25 UTC
