### ISSUE TITLE
Further clarification would be helpful on the 'Expressions' subpage, under the 'Escaping' section

### ISSUE THREAD

**Issue by jgvdangelo** [wycats/handlebars-site#143] opened 2016-02-18 17:56 UTC
First off - thank you for creating such an incredible library! I just had some minor pieces of feedback - that might help people adopt Handlebars quicker.On [this page](http://handlebarsjs.com/expressions.html), on the final section 'Escaping'.

The term 'escaping' here isn't very well-defined. Escape in terms of what? Is this notation for writing comments in your handlebars code? Or is this for HTML-escaping (I'm guessing not that, but one could suppose so)?

Perhaps the documentation be updated to explain this a little more? Thank you!

**Comment by nknapp** [comment] 2017-10-06 21:18
Duplicate of #142

**Closed by nknapp** 2017-10-06 21:18 UTC
